REMOTE_URL =    "http://127.0.0.1:4723"        
PLATFORM_NAME =  "Android"
PLATFORM_VERSION = "14.0"
DEVICE_NAME =     "Pixel a3"
APP_PACKAGE =          "com.groupeisi.ftgqatest"
APP_PACKAGES =         "com.mldiallo07.qatest"
APP_ACTIVITY   =    ".MainActivity"
AUTOMATION_NAME = "uiautomator2"
